#!/usr/bin/env python3
import argparse
import requests
import json

def get_argparser():
    parser = argparse.ArgumentParser(description="Data to send to state machine calculator")
    parser.add_argument('operation', choices=['addition', 'subtraction', 'multiplication', 'division'])
    parser.add_argument('x', help="x value")
    parser.add_argument('y', help="y value")
    return parser.parse_args()


if __name__ == '__main__':
    args = get_argparser()

    
    payload = json.dumps(
        {
            "operation": args.operation,
            "data": {
                "x": args.x,
                "y": args.y
            }
        }
    )

    '''
    TODO: fix this hehe
    r = requests.post("https://kuli565an5.execute-api.us-east-2.amazonaws.com/api/invoke", data=payload).json()

    print(r)
    '''
